require'nvim-treesitter.configs'.setup {
    ensure_installed = {
        "astro",
        "bash",
        "c",
        "c_sharp",
        "cmake",
        "cpp",
        "css",
        "dart",
        "dockerfile",
        "elixir",
        "git_rebase",
        "gitattributes",
        "gitcommit",
        "go",
        "graphql",
        "html",
        "http",
        "javascript",
        "json",
        "lua",
        "markdown",
        "prisma",
        "python",
        "regex",
        "rust",
        "scss",
        "solidity",
        "sql",
        "svelte",
        "toml",
        "tsx",
        "typescript",
        "vim",
        "vue",
        "yaml",
        "zig"
    },
    sync_install = false,
    highlight = {
        enable = true,
        additional_vim_regex_highlighting = false,
    },
}

